version: '3.8'

services:
  awx_file:
    image: ghcr.io/ansible/awx_devel:HEAD
    container_name: awx_container
    depends_on:
      - awx_db_file
      - redis_awx_file
    environment:
      DATABASE_HOST: awx_db_container
      DATABASE_NAME: awx
      DATABASE_USER: awx_user
      DATABASE_PASSWORD: awx_password
      REDIS_HOST: redis_container
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      HTTP_PORT: 8043
      HTTPS_PORT: 8443
    ports:
      - "8043:8043"
      - "8443:8443"

  awx_db_file:
    image: postgres:12
    container_name: awx_db_container
    environment:
      POSTGRES_DB: awx
      POSTGRES_USER: awx_user
      POSTGRES_PASSWORD: awx_password
    volumes:
      - awx_db_data:/var/lib/postgresql/data

  redis_awx_file:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_PASSWORD: redis_password
    command: ["redis-server", "--requirepass", "redis_password"]
    volumes:
      - redis_data:/data

volumes:
  awx_db_data:
  redis_data:
